services:
  postgres:
    image: postgres:16-alpine
    container_name: edupro-postgres
    environment:
      POSTGRES_DB: edupro
      POSTGRES_USER: edupro_migrator
      POSTGRES_PASSWORD: edupro_migrator_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U edupro_migrator -d edupro']
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: edupro-redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: edupro-mailpit
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres-data:
  redis-data:
