/**
 * Student profile field catalogue (generated from Student_Information_Collection.xlsx, Field Guide
 * sheet; School / Branch and the school UDISE code are deliberately left out). One definition drives
 * the edit form, API validation, completeness, the Excel import / update templates and the report
 * builder's student columns. Keys are stable: never rename a key that holds data.
 */

export type ProfileParty = 'student' | 'father' | 'mother' | 'guardian';
export type GuardianParty = Exclude<ProfileParty, 'student'>;
export type ProfileFieldType =
  | 'text'
  | 'date'
  | 'list'
  | 'number'
  | 'digits12'
  | 'digits11'
  | 'mobile'
  | 'pin'
  | 'email'
  | 'pan'
  | 'ifsc'
  | 'account'
  | 'year'
  | 'auto';

/** Where a value lives. */
export type ProfileStore =
  | { t: 'col'; col: string } // students column
  | { t: 'addr'; key: string } // students.address (residential address)
  | { t: 'json'; on: ProfileParty; key: string } // students.profile / guardians.profile
  | { t: 'secure'; on: ProfileParty; key: string } // encrypted: students.secure / guardians.secure
  | { t: 'gcol'; on: GuardianParty; col: string } // guardians column
  | { t: 'enrol'; col: string } // read from the enrolment of the year (changed through enrolment)
  | { t: 'auto' }; // computed

export interface ProfileField {
  key: string;
  section: ProfileSectionId;
  label: string;
  type: ProfileFieldType;
  /** Counts toward completeness (the sheet's "Required = Yes"), when the field applies. */
  required?: boolean;
  /** Dropdown list code (school-editable master `profile_lists`; State / Country / City come from the geography masters, Bank from the banks master). */
  list?: string;
  /** Stored in capitals. */
  upper?: boolean;
  help?: string;
  /** The field applies only when another field has (or has not) one of these values. */
  when?: { key: string; in?: string[]; notIn?: string[] };
  /** Encrypted at rest and masked unless the viewer holds people.sensitive.view. */
  sensitive?: boolean;
  /**
   * Kept for the data already on file and for reports, but no longer asked for: off the edit screens,
   * the Excel template, the portal and the profile PDF.
   */
  retired?: boolean;
  store: ProfileStore;
  /** Column letter in the data collection sheet. */
  excelColumn: string;
}

export const PROFILE_SECTIONS = [
  { id: 'student', title: 'Student' },
  { id: 'govt_ids', title: 'Government IDs' },
  { id: 'academic', title: 'Academic' },
  { id: 'previous_school', title: 'Previous school' },
  { id: 'father', title: 'Father' },
  { id: 'mother', title: 'Mother' },
  { id: 'guardian', title: 'Guardian' },
  { id: 'family', title: 'Family' },
  { id: 'address', title: 'Address' },
  { id: 'contact', title: 'Contact' },
  { id: 'sibling', title: 'Sibling' },
  { id: 'transport_health', title: 'Transport and health' },
  { id: 'bank', title: 'Bank details' },
  { id: 'documents', title: 'Documents' },
] as const;
export type ProfileSectionId = (typeof PROFILE_SECTIONS)[number]['id'];

export const PROFILE_FIELDS: ProfileField[] = [
  {
    key: 'registration_no',
    section: 'student',
    label: 'Registration No',
    type: 'text',
    required: true,
    help: 'Unique registration number',
    store: { t: 'json', on: 'student', key: 'registration_no' },
    excelColumn: 'B',
  },
  {
    key: 'admission_no',
    section: 'student',
    label: 'Admission No',
    type: 'text',
    help: 'Given after admission is confirmed',
    store: { t: 'col', col: 'admission_no' },
    excelColumn: 'C',
  },
  {
    key: 'first_name',
    section: 'student',
    label: 'First Name',
    type: 'text',
    required: true,
    upper: true,
    help: 'Student first name (CAPITALS)',
    store: { t: 'col', col: 'first_name' },
    excelColumn: 'D',
  },
  {
    key: 'middle_name',
    section: 'student',
    label: 'Middle Name',
    type: 'text',
    upper: true,
    store: { t: 'json', on: 'student', key: 'middle_name' },
    excelColumn: 'E',
  },
  {
    key: 'last_name',
    section: 'student',
    label: 'Last Name',
    type: 'text',
    upper: true,
    store: { t: 'col', col: 'last_name' },
    excelColumn: 'F',
  },
  {
    key: 'dob',
    section: 'student',
    label: 'Date of Birth',
    type: 'date',
    required: true,
    help: 'DD-MM-YYYY',
    store: { t: 'col', col: 'dob' },
    excelColumn: 'G',
  },
  {
    key: 'age',
    section: 'student',
    label: 'Age (as on 31 Mar)',
    type: 'auto',
    store: { t: 'auto' },
    excelColumn: 'H',
  },
  {
    key: 'gender',
    section: 'student',
    label: 'Gender',
    type: 'list',
    required: true,
    list: 'Gender',
    store: { t: 'col', col: 'gender' },
    excelColumn: 'I',
  },
  {
    key: 'blood_group',
    section: 'student',
    label: 'Blood Group',
    type: 'list',
    list: 'BloodGroup',
    store: { t: 'col', col: 'blood_group' },
    excelColumn: 'J',
  },
  {
    key: 'religion',
    section: 'student',
    label: 'Religion',
    type: 'list',
    list: 'Religion',
    store: { t: 'json', on: 'student', key: 'religion' },
    excelColumn: 'K',
  },
  {
    key: 'category',
    section: 'student',
    label: 'Caste Category',
    type: 'list',
    required: true,
    list: 'Category',
    store: { t: 'col', col: 'category' },
    excelColumn: 'L',
  },
  {
    key: 'sub_caste',
    section: 'student',
    label: 'Sub-Caste',
    type: 'list',
    list: 'SubCaste',
    store: { t: 'json', on: 'student', key: 'sub_caste' },
    excelColumn: 'M',
  },
  {
    key: 'caste_certificate_no',
    section: 'student',
    label: 'Caste Certificate No',
    type: 'text',
    help: 'Only for OBC / SC / ST',
    when: { key: 'category', in: ['OBC', 'OBC (Non-Creamy Layer)', 'SC', 'ST'] },
    store: { t: 'json', on: 'student', key: 'caste_certificate_no' },
    excelColumn: 'N',
  },
  {
    key: 'ews',
    section: 'student',
    label: 'EWS / DG Category',
    type: 'list',
    required: true,
    list: 'YesNo',
    help: 'Economically Weaker Section / Disadvantaged Group',
    store: { t: 'json', on: 'student', key: 'ews' },
    excelColumn: 'O',
  },
  {
    key: 'ews_certificate_no',
    section: 'student',
    label: 'EWS Certificate No',
    type: 'text',
    help: 'Only if EWS / DG = Yes',
    when: { key: 'ews', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'ews_certificate_no' },
    excelColumn: 'P',
  },
  {
    key: 'nationality',
    section: 'student',
    label: 'Nationality',
    type: 'list',
    required: true,
    list: 'Nationality',
    store: { t: 'json', on: 'student', key: 'nationality' },
    excelColumn: 'Q',
  },
  {
    key: 'mother_tongue',
    section: 'student',
    label: 'Mother Tongue',
    type: 'list',
    list: 'MotherTongue',
    store: { t: 'json', on: 'student', key: 'mother_tongue' },
    excelColumn: 'R',
  },
  {
    key: 'place_of_birth',
    section: 'student',
    label: 'Place of Birth',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'place_of_birth' },
    excelColumn: 'S',
  },
  {
    key: 'twin',
    section: 'student',
    label: 'Twin / Triplet',
    type: 'list',
    list: 'Twin',
    store: { t: 'json', on: 'student', key: 'twin' },
    excelColumn: 'T',
  },
  {
    key: 'photo_ref',
    retired: true,
    section: 'student',
    label: 'Student Photo (file name / link)',
    type: 'text',
    help: 'Photo file name or Drive link',
    store: { t: 'json', on: 'student', key: 'photo_ref' },
    excelColumn: 'U',
  },
  {
    key: 'aadhaar_no',
    section: 'govt_ids',
    label: 'Student Aadhaar No',
    type: 'digits12',
    help: '12 digits, no spaces',
    sensitive: true,
    store: { t: 'secure', on: 'student', key: 'aadhaar_no' },
    excelColumn: 'V',
  },
  {
    key: 'apaar_id',
    section: 'govt_ids',
    label: 'APAAR ID',
    type: 'digits12',
    help: '12-digit APAAR ID',
    store: { t: 'json', on: 'student', key: 'apaar_id' },
    excelColumn: 'W',
  },
  {
    key: 'pen_no',
    section: 'govt_ids',
    label: 'PEN No',
    type: 'text',
    help: 'Permanent Education Number (UDISE+)',
    store: { t: 'json', on: 'student', key: 'pen_no' },
    excelColumn: 'X',
  },
  {
    key: 'srn_no',
    section: 'govt_ids',
    label: 'SRN No',
    type: 'text',
    help: 'Student Registration No (Directorate of Education)',
    store: { t: 'json', on: 'student', key: 'srn_no' },
    excelColumn: 'Y',
  },
  {
    key: 'academic_year',
    section: 'academic',
    label: 'Academic Year',
    type: 'text',
    required: true,
    help: 'Format YYYY-YY',
    store: { t: 'enrol', col: 'academic_year' },
    excelColumn: 'AA',
  },
  {
    key: 'class',
    section: 'academic',
    label: 'Class',
    type: 'list',
    required: true,
    list: 'Class',
    help: 'Class applied / admitted',
    store: { t: 'enrol', col: 'class' },
    excelColumn: 'AC',
  },
  {
    key: 'section',
    section: 'academic',
    label: 'Section',
    type: 'text',
    help: 'Single letter',
    store: { t: 'enrol', col: 'section' },
    excelColumn: 'AD',
  },
  {
    key: 'roll_no',
    section: 'academic',
    label: 'Roll No',
    type: 'number',
    store: { t: 'enrol', col: 'roll_no' },
    excelColumn: 'AE',
  },
  {
    key: 'stream',
    section: 'academic',
    label: 'Stream (XI-XII)',
    type: 'list',
    list: 'Stream',
    help: 'Only for Class XI / XII',
    store: { t: 'json', on: 'student', key: 'stream' },
    excelColumn: 'AF',
  },
  {
    key: 'registration_date',
    section: 'academic',
    label: 'Registration Date',
    type: 'date',
    required: true,
    help: 'DD-MM-YYYY',
    store: { t: 'json', on: 'student', key: 'registration_date' },
    excelColumn: 'AG',
  },
  {
    key: 'admitted_on',
    section: 'academic',
    label: 'Date of Admission',
    type: 'date',
    help: 'DD-MM-YYYY',
    store: { t: 'col', col: 'admitted_on' },
    excelColumn: 'AH',
  },
  {
    key: 'house',
    section: 'academic',
    label: 'House',
    type: 'list',
    list: 'House',
    help: 'School house for sports and activities',
    store: { t: 'col', col: 'house' },
    excelColumn: '—',
  },
  {
    key: 'boarding',
    section: 'academic',
    label: 'Day Scholar / Hosteller',
    type: 'list',
    required: true,
    list: 'Boarding',
    store: { t: 'json', on: 'student', key: 'boarding' },
    excelColumn: 'AI',
  },
  {
    key: 'previous_school_name',
    section: 'previous_school',
    label: 'Previous School Name',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'previous_school_name' },
    excelColumn: 'AJ',
  },
  {
    key: 'previous_school_city_state',
    section: 'previous_school',
    label: 'Previous School City / State',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'previous_school_city_state' },
    excelColumn: 'AK',
  },
  {
    key: 'previous_school_board',
    section: 'previous_school',
    label: 'Previous School Board',
    type: 'list',
    list: 'Board',
    help: 'Affiliation board',
    store: { t: 'json', on: 'student', key: 'previous_school_board' },
    excelColumn: 'AL',
  },
  {
    key: 'previous_school_affiliation_no',
    section: 'previous_school',
    label: 'Previous School Affiliation No',
    type: 'text',
    help: 'Board affiliation number',
    store: { t: 'json', on: 'student', key: 'previous_school_affiliation_no' },
    excelColumn: 'AM',
  },
  {
    key: 'previous_school_udise_code',
    section: 'previous_school',
    label: 'Previous School UDISE Code',
    type: 'digits11',
    store: { t: 'json', on: 'student', key: 'previous_school_udise_code' },
    excelColumn: 'AN',
  },
  {
    key: 'last_class_attended',
    section: 'previous_school',
    label: 'Last Class Attended',
    type: 'list',
    list: 'Class',
    store: { t: 'json', on: 'student', key: 'last_class_attended' },
    excelColumn: 'AO',
  },
  {
    key: 'previous_school_admission_no',
    section: 'previous_school',
    label: 'Previous School Admission No',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'previous_school_admission_no' },
    excelColumn: 'AP',
  },
  {
    key: 'tc_no',
    section: 'previous_school',
    label: 'TC No',
    type: 'text',
    help: 'Transfer Certificate number',
    store: { t: 'json', on: 'student', key: 'tc_no' },
    excelColumn: 'AQ',
  },
  {
    key: 'tc_date',
    section: 'previous_school',
    label: 'TC Date',
    type: 'date',
    help: 'DD-MM-YYYY',
    store: { t: 'json', on: 'student', key: 'tc_date' },
    excelColumn: 'AR',
  },
  {
    key: 'father_name',
    section: 'father',
    label: "Father's Name",
    type: 'text',
    required: true,
    upper: true,
    help: 'CAPITAL LETTERS',
    store: { t: 'gcol', on: 'father', col: 'first_name' },
    excelColumn: 'AS',
  },
  {
    key: 'father_date_of_birth',
    section: 'father',
    label: "Father's Date of Birth",
    type: 'date',
    help: 'DD-MM-YYYY',
    store: { t: 'json', on: 'father', key: 'date_of_birth' },
    excelColumn: 'AT',
  },
  {
    key: 'father_nationality',
    section: 'father',
    label: "Father's Nationality",
    type: 'list',
    list: 'Nationality',
    store: { t: 'json', on: 'father', key: 'nationality' },
    excelColumn: 'AU',
  },
  {
    key: 'father_photo',
    retired: true,
    section: 'father',
    label: "Father's Photo (file name / link)",
    type: 'text',
    help: 'Photo file name or Drive link',
    store: { t: 'json', on: 'father', key: 'photo' },
    excelColumn: 'AV',
  },
  {
    key: 'father_mobile',
    section: 'father',
    label: "Father's Mobile",
    type: 'mobile',
    required: true,
    help: '10 digits, no +91 or 0',
    store: { t: 'gcol', on: 'father', col: 'mobile' },
    excelColumn: 'AW',
  },
  {
    key: 'father_whatsapp_no',
    section: 'father',
    label: "Father's WhatsApp No",
    type: 'mobile',
    help: 'Leave blank if same as mobile',
    store: { t: 'json', on: 'father', key: 'whatsapp_no' },
    excelColumn: 'AX',
  },
  {
    key: 'father_email',
    section: 'father',
    label: "Father's Email",
    type: 'email',
    store: { t: 'gcol', on: 'father', col: 'email' },
    excelColumn: 'AY',
  },
  {
    key: 'father_mobile_for_sms_calls',
    section: 'father',
    label: "Father's Mobile for SMS / Calls",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = school SMS / calls go to this mobile',
    store: { t: 'json', on: 'father', key: 'mobile_for_sms_calls' },
    excelColumn: 'AZ',
  },
  {
    key: 'father_email_for_communication',
    section: 'father',
    label: "Father's Email for Communication",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = school emails go to this email',
    store: { t: 'json', on: 'father', key: 'email_for_communication' },
    excelColumn: 'BA',
  },
  {
    key: 'father_emergency_contact',
    section: 'father',
    label: "Father's Emergency Contact",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = call this person in an emergency',
    store: { t: 'json', on: 'father', key: 'emergency_contact' },
    excelColumn: 'BB',
  },
  {
    key: 'father_pan_no',
    section: 'father',
    label: "Father's PAN No",
    type: 'pan',
    help: '10 characters, e.g. ABCDE1234F',
    sensitive: true,
    store: { t: 'secure', on: 'father', key: 'pan_no' },
    excelColumn: 'BC',
  },
  {
    key: 'father_aadhaar_no',
    section: 'father',
    label: "Father's Aadhaar No",
    type: 'digits12',
    help: '12 digits, no spaces',
    sensitive: true,
    store: { t: 'secure', on: 'father', key: 'aadhaar_no' },
    excelColumn: 'BD',
  },
  {
    key: 'father_education',
    section: 'father',
    label: "Father's Education",
    type: 'list',
    list: 'Education',
    store: { t: 'json', on: 'father', key: 'education' },
    excelColumn: 'BE',
  },
  {
    key: 'father_occupation',
    section: 'father',
    label: "Father's Occupation",
    type: 'list',
    required: true,
    list: 'Occupation',
    store: { t: 'gcol', on: 'father', col: 'occupation' },
    excelColumn: 'BF',
  },
  {
    key: 'father_designation',
    section: 'father',
    label: "Father's Designation",
    type: 'text',
    store: { t: 'json', on: 'father', key: 'designation' },
    excelColumn: 'BG',
  },
  {
    key: 'father_organisation',
    section: 'father',
    label: "Father's Organisation",
    type: 'text',
    store: { t: 'json', on: 'father', key: 'organisation' },
    excelColumn: 'BH',
  },
  {
    key: 'father_annual_income',
    section: 'father',
    label: "Father's Annual Income",
    type: 'list',
    list: 'Income',
    store: { t: 'json', on: 'father', key: 'annual_income' },
    excelColumn: 'BI',
  },
  {
    key: 'father_office_address_line_1',
    section: 'father',
    label: "Father's Office Address Line 1",
    type: 'text',
    help: 'House / flat no, building, street',
    store: { t: 'json', on: 'father', key: 'office_address_line_1' },
    excelColumn: 'BJ',
  },
  {
    key: 'father_office_address_line_2',
    section: 'father',
    label: "Father's Office Address Line 2",
    type: 'text',
    help: 'Area / locality / colony',
    store: { t: 'json', on: 'father', key: 'office_address_line_2' },
    excelColumn: 'BK',
  },
  {
    key: 'father_office_address_line_3',
    section: 'father',
    label: "Father's Office Address Line 3",
    type: 'text',
    help: 'Landmark (optional)',
    store: { t: 'json', on: 'father', key: 'office_address_line_3' },
    excelColumn: 'BL',
  },
  {
    key: 'father_office_city',
    section: 'father',
    label: "Father's Office City",
    type: 'list',
    list: 'City',
    store: { t: 'json', on: 'father', key: 'office_city' },
    excelColumn: 'BM',
  },
  {
    key: 'father_office_state',
    section: 'father',
    label: "Father's Office State",
    type: 'list',
    list: 'State',
    store: { t: 'json', on: 'father', key: 'office_state' },
    excelColumn: 'BN',
  },
  {
    key: 'father_office_country',
    section: 'father',
    label: "Father's Office Country",
    type: 'list',
    list: 'Country',
    store: { t: 'json', on: 'father', key: 'office_country' },
    excelColumn: 'BO',
  },
  {
    key: 'father_office_pin_code',
    section: 'father',
    label: "Father's Office PIN Code",
    type: 'pin',
    help: '6 digits',
    store: { t: 'json', on: 'father', key: 'office_pin_code' },
    excelColumn: 'BP',
  },
  {
    key: 'father_dps_alumni',
    section: 'father',
    label: 'Father is an Alumnus',
    type: 'list',
    list: 'YesNo',
    help: 'Studied at this school or a school of the same group',
    store: { t: 'json', on: 'father', key: 'dps_alumni' },
    excelColumn: 'BQ',
  },
  {
    key: 'father_alumni_school_branch',
    section: 'father',
    label: 'Father Alumni School & Branch',
    type: 'text',
    help: 'Only if alumni — the school and branch, e.g. Delhi Road branch',
    when: { key: 'father_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'father', key: 'alumni_school_branch' },
    excelColumn: 'BR',
  },
  {
    key: 'father_alumni_school_city_state',
    section: 'father',
    label: 'Father Alumni School City / State',
    type: 'text',
    help: 'Only if alumni — e.g. Bokaro, Jharkhand',
    when: { key: 'father_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'father', key: 'alumni_school_city_state' },
    excelColumn: 'BS',
  },
  {
    key: 'father_alumni_passing_class',
    section: 'father',
    label: 'Father Alumni Passing Class',
    type: 'list',
    list: 'AlumniClass',
    help: 'Class X or XII',
    when: { key: 'father_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'father', key: 'alumni_passing_class' },
    excelColumn: 'BT',
  },
  {
    key: 'father_alumni_passing_year',
    section: 'father',
    label: 'Father Alumni Passing Year',
    type: 'year',
    help: '4-digit year',
    when: { key: 'father_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'father', key: 'alumni_passing_year' },
    excelColumn: 'BU',
  },
  {
    key: 'father_alumni_cbse_roll_no',
    section: 'father',
    label: 'Father Alumni CBSE Roll No',
    type: 'text',
    help: 'CBSE board roll no of Class X / XII',
    when: { key: 'father_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'father', key: 'alumni_cbse_roll_no' },
    excelColumn: 'BV',
  },
  {
    key: 'father_school_staff',
    section: 'father',
    label: 'Father is School Staff',
    type: 'list',
    required: true,
    list: 'YesNo',
    help: 'Yes if father works in this school',
    store: { t: 'json', on: 'father', key: 'school_staff' },
    excelColumn: 'BW',
  },
  {
    key: 'father_staff_employee_id',
    section: 'father',
    label: 'Father Staff Employee ID',
    type: 'text',
    help: 'Only if Father is School Staff = Yes',
    when: { key: 'father_school_staff', in: ['Yes'] },
    store: { t: 'json', on: 'father', key: 'staff_employee_id' },
    excelColumn: 'BX',
  },
  {
    key: 'mother_name',
    section: 'mother',
    label: "Mother's Name",
    type: 'text',
    required: true,
    upper: true,
    help: 'CAPITAL LETTERS',
    store: { t: 'gcol', on: 'mother', col: 'first_name' },
    excelColumn: 'BY',
  },
  {
    key: 'mother_date_of_birth',
    section: 'mother',
    label: "Mother's Date of Birth",
    type: 'date',
    help: 'DD-MM-YYYY',
    store: { t: 'json', on: 'mother', key: 'date_of_birth' },
    excelColumn: 'BZ',
  },
  {
    key: 'mother_nationality',
    section: 'mother',
    label: "Mother's Nationality",
    type: 'list',
    list: 'Nationality',
    store: { t: 'json', on: 'mother', key: 'nationality' },
    excelColumn: 'CA',
  },
  {
    key: 'mother_photo',
    retired: true,
    section: 'mother',
    label: "Mother's Photo (file name / link)",
    type: 'text',
    help: 'Photo file name or Drive link',
    store: { t: 'json', on: 'mother', key: 'photo' },
    excelColumn: 'CB',
  },
  {
    key: 'mother_mobile',
    section: 'mother',
    label: "Mother's Mobile",
    type: 'mobile',
    required: true,
    help: '10 digits, no +91 or 0',
    store: { t: 'gcol', on: 'mother', col: 'mobile' },
    excelColumn: 'CC',
  },
  {
    key: 'mother_whatsapp_no',
    section: 'mother',
    label: "Mother's WhatsApp No",
    type: 'mobile',
    help: 'Leave blank if same as mobile',
    store: { t: 'json', on: 'mother', key: 'whatsapp_no' },
    excelColumn: 'CD',
  },
  {
    key: 'mother_email',
    section: 'mother',
    label: "Mother's Email",
    type: 'email',
    store: { t: 'gcol', on: 'mother', col: 'email' },
    excelColumn: 'CE',
  },
  {
    key: 'mother_mobile_for_sms_calls',
    section: 'mother',
    label: "Mother's Mobile for SMS / Calls",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = school SMS / calls go to this mobile',
    store: { t: 'json', on: 'mother', key: 'mobile_for_sms_calls' },
    excelColumn: 'CF',
  },
  {
    key: 'mother_email_for_communication',
    section: 'mother',
    label: "Mother's Email for Communication",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = school emails go to this email',
    store: { t: 'json', on: 'mother', key: 'email_for_communication' },
    excelColumn: 'CG',
  },
  {
    key: 'mother_emergency_contact',
    section: 'mother',
    label: "Mother's Emergency Contact",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = call this person in an emergency',
    store: { t: 'json', on: 'mother', key: 'emergency_contact' },
    excelColumn: 'CH',
  },
  {
    key: 'mother_pan_no',
    section: 'mother',
    label: "Mother's PAN No",
    type: 'pan',
    help: '10 characters, e.g. ABCDE1234F',
    sensitive: true,
    store: { t: 'secure', on: 'mother', key: 'pan_no' },
    excelColumn: 'CI',
  },
  {
    key: 'mother_aadhaar_no',
    section: 'mother',
    label: "Mother's Aadhaar No",
    type: 'digits12',
    help: '12 digits, no spaces',
    sensitive: true,
    store: { t: 'secure', on: 'mother', key: 'aadhaar_no' },
    excelColumn: 'CJ',
  },
  {
    key: 'mother_education',
    section: 'mother',
    label: "Mother's Education",
    type: 'list',
    list: 'Education',
    store: { t: 'json', on: 'mother', key: 'education' },
    excelColumn: 'CK',
  },
  {
    key: 'mother_occupation',
    section: 'mother',
    label: "Mother's Occupation",
    type: 'list',
    required: true,
    list: 'Occupation',
    store: { t: 'gcol', on: 'mother', col: 'occupation' },
    excelColumn: 'CL',
  },
  {
    key: 'mother_designation',
    section: 'mother',
    label: "Mother's Designation",
    type: 'text',
    store: { t: 'json', on: 'mother', key: 'designation' },
    excelColumn: 'CM',
  },
  {
    key: 'mother_organisation',
    section: 'mother',
    label: "Mother's Organisation",
    type: 'text',
    store: { t: 'json', on: 'mother', key: 'organisation' },
    excelColumn: 'CN',
  },
  {
    key: 'mother_annual_income',
    section: 'mother',
    label: "Mother's Annual Income",
    type: 'list',
    list: 'Income',
    store: { t: 'json', on: 'mother', key: 'annual_income' },
    excelColumn: 'CO',
  },
  {
    key: 'mother_office_address_line_1',
    section: 'mother',
    label: "Mother's Office Address Line 1",
    type: 'text',
    help: 'House / flat no, building, street',
    store: { t: 'json', on: 'mother', key: 'office_address_line_1' },
    excelColumn: 'CP',
  },
  {
    key: 'mother_office_address_line_2',
    section: 'mother',
    label: "Mother's Office Address Line 2",
    type: 'text',
    help: 'Area / locality / colony',
    store: { t: 'json', on: 'mother', key: 'office_address_line_2' },
    excelColumn: 'CQ',
  },
  {
    key: 'mother_office_address_line_3',
    section: 'mother',
    label: "Mother's Office Address Line 3",
    type: 'text',
    help: 'Landmark (optional)',
    store: { t: 'json', on: 'mother', key: 'office_address_line_3' },
    excelColumn: 'CR',
  },
  {
    key: 'mother_office_city',
    section: 'mother',
    label: "Mother's Office City",
    type: 'list',
    list: 'City',
    store: { t: 'json', on: 'mother', key: 'office_city' },
    excelColumn: 'CS',
  },
  {
    key: 'mother_office_state',
    section: 'mother',
    label: "Mother's Office State",
    type: 'list',
    list: 'State',
    store: { t: 'json', on: 'mother', key: 'office_state' },
    excelColumn: 'CT',
  },
  {
    key: 'mother_office_country',
    section: 'mother',
    label: "Mother's Office Country",
    type: 'list',
    list: 'Country',
    store: { t: 'json', on: 'mother', key: 'office_country' },
    excelColumn: 'CU',
  },
  {
    key: 'mother_office_pin_code',
    section: 'mother',
    label: "Mother's Office PIN Code",
    type: 'pin',
    help: '6 digits',
    store: { t: 'json', on: 'mother', key: 'office_pin_code' },
    excelColumn: 'CV',
  },
  {
    key: 'mother_dps_alumni',
    section: 'mother',
    label: 'Mother is an Alumnus',
    type: 'list',
    list: 'YesNo',
    help: 'Studied at this school or a school of the same group',
    store: { t: 'json', on: 'mother', key: 'dps_alumni' },
    excelColumn: 'CW',
  },
  {
    key: 'mother_alumni_school_branch',
    section: 'mother',
    label: 'Mother Alumni School & Branch',
    type: 'text',
    help: 'Only if alumni — the school and branch, e.g. Delhi Road branch',
    when: { key: 'mother_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'mother', key: 'alumni_school_branch' },
    excelColumn: 'CX',
  },
  {
    key: 'mother_alumni_school_city_state',
    section: 'mother',
    label: 'Mother Alumni School City / State',
    type: 'text',
    help: 'Only if alumni — e.g. Bokaro, Jharkhand',
    when: { key: 'mother_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'mother', key: 'alumni_school_city_state' },
    excelColumn: 'CY',
  },
  {
    key: 'mother_alumni_passing_class',
    section: 'mother',
    label: 'Mother Alumni Passing Class',
    type: 'list',
    list: 'AlumniClass',
    help: 'Class X or XII',
    when: { key: 'mother_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'mother', key: 'alumni_passing_class' },
    excelColumn: 'CZ',
  },
  {
    key: 'mother_alumni_passing_year',
    section: 'mother',
    label: 'Mother Alumni Passing Year',
    type: 'year',
    help: '4-digit year',
    when: { key: 'mother_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'mother', key: 'alumni_passing_year' },
    excelColumn: 'DA',
  },
  {
    key: 'mother_alumni_cbse_roll_no',
    section: 'mother',
    label: 'Mother Alumni CBSE Roll No',
    type: 'text',
    help: 'CBSE board roll no of Class X / XII',
    when: { key: 'mother_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'mother', key: 'alumni_cbse_roll_no' },
    excelColumn: 'DB',
  },
  {
    key: 'mother_school_staff',
    section: 'mother',
    label: 'Mother is School Staff',
    type: 'list',
    required: true,
    list: 'YesNo',
    help: 'Yes if mother works in this school',
    store: { t: 'json', on: 'mother', key: 'school_staff' },
    excelColumn: 'DC',
  },
  {
    key: 'mother_staff_employee_id',
    section: 'mother',
    label: 'Mother Staff Employee ID',
    type: 'text',
    help: 'Only if Mother is School Staff = Yes',
    when: { key: 'mother_school_staff', in: ['Yes'] },
    store: { t: 'json', on: 'mother', key: 'staff_employee_id' },
    excelColumn: 'DD',
  },
  {
    key: 'guardian_name',
    section: 'guardian',
    label: "Guardian's Name",
    type: 'text',
    upper: true,
    help: 'CAPITAL LETTERS',
    store: { t: 'gcol', on: 'guardian', col: 'first_name' },
    excelColumn: 'DE',
  },
  {
    key: 'guardian_relation',
    section: 'guardian',
    label: "Guardian's Relation with Student",
    type: 'list',
    list: 'Relation',
    help: 'Fill guardian block only if guardian is not father / mother',
    store: { t: 'json', on: 'guardian', key: 'relation' },
    excelColumn: 'DF',
  },
  {
    key: 'guardian_date_of_birth',
    section: 'guardian',
    label: "Guardian's Date of Birth",
    type: 'date',
    help: 'DD-MM-YYYY',
    store: { t: 'json', on: 'guardian', key: 'date_of_birth' },
    excelColumn: 'DG',
  },
  {
    key: 'guardian_nationality',
    section: 'guardian',
    label: "Guardian's Nationality",
    type: 'list',
    list: 'Nationality',
    store: { t: 'json', on: 'guardian', key: 'nationality' },
    excelColumn: 'DH',
  },
  {
    key: 'guardian_photo',
    retired: true,
    section: 'guardian',
    label: "Guardian's Photo (file name / link)",
    type: 'text',
    help: 'Photo file name or Drive link',
    store: { t: 'json', on: 'guardian', key: 'photo' },
    excelColumn: 'DI',
  },
  {
    key: 'guardian_mobile',
    section: 'guardian',
    label: "Guardian's Mobile",
    type: 'mobile',
    help: '10 digits, no +91 or 0',
    store: { t: 'gcol', on: 'guardian', col: 'mobile' },
    excelColumn: 'DJ',
  },
  {
    key: 'guardian_whatsapp_no',
    section: 'guardian',
    label: "Guardian's WhatsApp No",
    type: 'mobile',
    help: 'Leave blank if same as mobile',
    store: { t: 'json', on: 'guardian', key: 'whatsapp_no' },
    excelColumn: 'DK',
  },
  {
    key: 'guardian_email',
    section: 'guardian',
    label: "Guardian's Email",
    type: 'email',
    store: { t: 'gcol', on: 'guardian', col: 'email' },
    excelColumn: 'DL',
  },
  {
    key: 'guardian_mobile_for_sms_calls',
    section: 'guardian',
    label: "Guardian's Mobile for SMS / Calls",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = school SMS / calls go to this mobile',
    store: { t: 'json', on: 'guardian', key: 'mobile_for_sms_calls' },
    excelColumn: 'DM',
  },
  {
    key: 'guardian_email_for_communication',
    section: 'guardian',
    label: "Guardian's Email for Communication",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = school emails go to this email',
    store: { t: 'json', on: 'guardian', key: 'email_for_communication' },
    excelColumn: 'DN',
  },
  {
    key: 'guardian_emergency_contact',
    section: 'guardian',
    label: "Guardian's Emergency Contact",
    type: 'list',
    list: 'YesNo',
    help: 'Yes = call this person in an emergency',
    store: { t: 'json', on: 'guardian', key: 'emergency_contact' },
    excelColumn: 'DO',
  },
  {
    key: 'guardian_pan_no',
    section: 'guardian',
    label: "Guardian's PAN No",
    type: 'pan',
    help: '10 characters, e.g. ABCDE1234F',
    sensitive: true,
    store: { t: 'secure', on: 'guardian', key: 'pan_no' },
    excelColumn: 'DP',
  },
  {
    key: 'guardian_aadhaar_no',
    section: 'guardian',
    label: "Guardian's Aadhaar No",
    type: 'digits12',
    help: '12 digits, no spaces',
    sensitive: true,
    store: { t: 'secure', on: 'guardian', key: 'aadhaar_no' },
    excelColumn: 'DQ',
  },
  {
    key: 'guardian_education',
    section: 'guardian',
    label: "Guardian's Education",
    type: 'list',
    list: 'Education',
    store: { t: 'json', on: 'guardian', key: 'education' },
    excelColumn: 'DR',
  },
  {
    key: 'guardian_occupation',
    section: 'guardian',
    label: "Guardian's Occupation",
    type: 'list',
    list: 'Occupation',
    store: { t: 'gcol', on: 'guardian', col: 'occupation' },
    excelColumn: 'DS',
  },
  {
    key: 'guardian_designation',
    section: 'guardian',
    label: "Guardian's Designation",
    type: 'text',
    store: { t: 'json', on: 'guardian', key: 'designation' },
    excelColumn: 'DT',
  },
  {
    key: 'guardian_organisation',
    section: 'guardian',
    label: "Guardian's Organisation",
    type: 'text',
    store: { t: 'json', on: 'guardian', key: 'organisation' },
    excelColumn: 'DU',
  },
  {
    key: 'guardian_annual_income',
    section: 'guardian',
    label: "Guardian's Annual Income",
    type: 'list',
    list: 'Income',
    store: { t: 'json', on: 'guardian', key: 'annual_income' },
    excelColumn: 'DV',
  },
  {
    key: 'guardian_office_address_line_1',
    section: 'guardian',
    label: "Guardian's Office Address Line 1",
    type: 'text',
    help: 'House / flat no, building, street',
    store: { t: 'json', on: 'guardian', key: 'office_address_line_1' },
    excelColumn: 'DW',
  },
  {
    key: 'guardian_office_address_line_2',
    section: 'guardian',
    label: "Guardian's Office Address Line 2",
    type: 'text',
    help: 'Area / locality / colony',
    store: { t: 'json', on: 'guardian', key: 'office_address_line_2' },
    excelColumn: 'DX',
  },
  {
    key: 'guardian_office_address_line_3',
    section: 'guardian',
    label: "Guardian's Office Address Line 3",
    type: 'text',
    help: 'Landmark (optional)',
    store: { t: 'json', on: 'guardian', key: 'office_address_line_3' },
    excelColumn: 'DY',
  },
  {
    key: 'guardian_office_city',
    section: 'guardian',
    label: "Guardian's Office City",
    type: 'list',
    list: 'City',
    store: { t: 'json', on: 'guardian', key: 'office_city' },
    excelColumn: 'DZ',
  },
  {
    key: 'guardian_office_state',
    section: 'guardian',
    label: "Guardian's Office State",
    type: 'list',
    list: 'State',
    store: { t: 'json', on: 'guardian', key: 'office_state' },
    excelColumn: 'EA',
  },
  {
    key: 'guardian_office_country',
    section: 'guardian',
    label: "Guardian's Office Country",
    type: 'list',
    list: 'Country',
    store: { t: 'json', on: 'guardian', key: 'office_country' },
    excelColumn: 'EB',
  },
  {
    key: 'guardian_office_pin_code',
    section: 'guardian',
    label: "Guardian's Office PIN Code",
    type: 'pin',
    help: '6 digits',
    store: { t: 'json', on: 'guardian', key: 'office_pin_code' },
    excelColumn: 'EC',
  },
  {
    key: 'guardian_dps_alumni',
    section: 'guardian',
    label: 'Guardian is an Alumnus',
    type: 'list',
    list: 'YesNo',
    help: 'Studied at this school or a school of the same group',
    store: { t: 'json', on: 'guardian', key: 'dps_alumni' },
    excelColumn: 'ED',
  },
  {
    key: 'guardian_alumni_school_branch',
    section: 'guardian',
    label: 'Guardian Alumni School & Branch',
    type: 'text',
    help: 'Only if alumni — the school and branch, e.g. Delhi Road branch',
    when: { key: 'guardian_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'guardian', key: 'alumni_school_branch' },
    excelColumn: 'EE',
  },
  {
    key: 'guardian_alumni_school_city_state',
    section: 'guardian',
    label: 'Guardian Alumni School City / State',
    type: 'text',
    help: 'Only if alumni — e.g. Bokaro, Jharkhand',
    when: { key: 'guardian_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'guardian', key: 'alumni_school_city_state' },
    excelColumn: 'EF',
  },
  {
    key: 'guardian_alumni_passing_class',
    section: 'guardian',
    label: 'Guardian Alumni Passing Class',
    type: 'list',
    list: 'AlumniClass',
    help: 'Class X or XII',
    when: { key: 'guardian_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'guardian', key: 'alumni_passing_class' },
    excelColumn: 'EG',
  },
  {
    key: 'guardian_alumni_passing_year',
    section: 'guardian',
    label: 'Guardian Alumni Passing Year',
    type: 'year',
    help: '4-digit year',
    when: { key: 'guardian_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'guardian', key: 'alumni_passing_year' },
    excelColumn: 'EH',
  },
  {
    key: 'guardian_alumni_cbse_roll_no',
    section: 'guardian',
    label: 'Guardian Alumni CBSE Roll No',
    type: 'text',
    help: 'CBSE board roll no of Class X / XII',
    when: { key: 'guardian_dps_alumni', in: ['Yes'] },
    store: { t: 'json', on: 'guardian', key: 'alumni_cbse_roll_no' },
    excelColumn: 'EI',
  },
  {
    key: 'guardian_school_staff',
    section: 'guardian',
    label: 'Guardian is School Staff',
    type: 'list',
    list: 'YesNo',
    help: 'Yes if guardian works in this school',
    store: { t: 'json', on: 'guardian', key: 'school_staff' },
    excelColumn: 'EJ',
  },
  {
    key: 'guardian_staff_employee_id',
    section: 'guardian',
    label: 'Guardian Staff Employee ID',
    type: 'text',
    help: 'Only if Guardian is School Staff = Yes',
    when: { key: 'guardian_school_staff', in: ['Yes'] },
    store: { t: 'json', on: 'guardian', key: 'staff_employee_id' },
    excelColumn: 'EK',
  },
  {
    key: 'single_parent',
    section: 'family',
    label: 'Single Parent',
    type: 'list',
    list: 'SingleParent',
    store: { t: 'json', on: 'student', key: 'single_parent' },
    excelColumn: 'EL',
  },
  {
    key: 'family_income',
    section: 'family',
    label: 'Family Gross Annual Income (Rs)',
    type: 'list',
    list: 'Income',
    required: true,
    help: 'Total yearly income of the family',
    store: { t: 'json', on: 'student', key: 'family_income' },
    excelColumn: 'EM',
  },
  {
    key: 'staff_ward',
    section: 'family',
    label: 'Staff Ward',
    type: 'auto',
    store: { t: 'auto' },
    excelColumn: 'EN',
  },
  {
    key: 'residential_address_line_1',
    section: 'address',
    label: 'Residential Address Line 1',
    type: 'text',
    required: true,
    help: 'House / flat no, building, street',
    store: { t: 'addr', key: 'line1' },
    excelColumn: 'EO',
  },
  {
    key: 'residential_address_line_2',
    section: 'address',
    label: 'Residential Address Line 2',
    type: 'text',
    help: 'Area / locality / colony',
    store: { t: 'addr', key: 'line2' },
    excelColumn: 'EP',
  },
  {
    key: 'residential_address_line_3',
    section: 'address',
    label: 'Residential Address Line 3',
    type: 'text',
    help: 'Landmark (optional)',
    store: { t: 'addr', key: 'line3' },
    excelColumn: 'EQ',
  },
  {
    key: 'residential_city',
    section: 'address',
    label: 'Residential City',
    type: 'list',
    list: 'City',
    required: true,
    store: { t: 'addr', key: 'city' },
    excelColumn: 'ER',
  },
  {
    key: 'residential_state',
    section: 'address',
    label: 'Residential State',
    type: 'list',
    required: true,
    list: 'State',
    store: { t: 'addr', key: 'state' },
    excelColumn: 'ES',
  },
  {
    key: 'residential_country',
    section: 'address',
    label: 'Residential Country',
    type: 'list',
    required: true,
    list: 'Country',
    store: { t: 'addr', key: 'country' },
    excelColumn: 'ET',
  },
  {
    key: 'residential_pin_code',
    section: 'address',
    label: 'Residential PIN Code',
    type: 'pin',
    required: true,
    help: '6 digits',
    store: { t: 'addr', key: 'pin' },
    excelColumn: 'EU',
  },
  {
    key: 'permanent_same',
    section: 'address',
    label: 'Permanent Same as Residential',
    type: 'list',
    list: 'YesNo',
    help: 'Yes = leave permanent address blank',
    store: { t: 'json', on: 'student', key: 'permanent_same' },
    excelColumn: 'EV',
  },
  {
    key: 'permanent_address_line_1',
    section: 'address',
    label: 'Permanent Address Line 1',
    type: 'text',
    help: 'House / flat no, building, street',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_address_line_1' },
    excelColumn: 'EW',
  },
  {
    key: 'permanent_address_line_2',
    section: 'address',
    label: 'Permanent Address Line 2',
    type: 'text',
    help: 'Area / locality / colony',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_address_line_2' },
    excelColumn: 'EX',
  },
  {
    key: 'permanent_address_line_3',
    section: 'address',
    label: 'Permanent Address Line 3',
    type: 'text',
    help: 'Landmark (optional)',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_address_line_3' },
    excelColumn: 'EY',
  },
  {
    key: 'permanent_city',
    section: 'address',
    label: 'Permanent City',
    type: 'list',
    list: 'City',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_city' },
    excelColumn: 'EZ',
  },
  {
    key: 'permanent_state',
    section: 'address',
    label: 'Permanent State',
    type: 'list',
    list: 'State',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_state' },
    excelColumn: 'FA',
  },
  {
    key: 'permanent_country',
    section: 'address',
    label: 'Permanent Country',
    type: 'list',
    list: 'Country',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_country' },
    excelColumn: 'FB',
  },
  {
    key: 'permanent_pin_code',
    section: 'address',
    label: 'Permanent PIN Code',
    type: 'pin',
    help: '6 digits',
    when: { key: 'permanent_same', notIn: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'permanent_pin_code' },
    excelColumn: 'FC',
  },
  {
    key: 'distance_from_school',
    section: 'address',
    label: 'Distance from School',
    type: 'list',
    list: 'Distance',
    store: { t: 'json', on: 'student', key: 'distance_from_school' },
    excelColumn: 'FD',
  },
  {
    key: 'sms_mobile',
    section: 'contact',
    label: 'SMS Mobile (Primary)',
    type: 'mobile',
    required: true,
    help: 'Main number for school SMS',
    store: { t: 'json', on: 'student', key: 'sms_mobile' },
    excelColumn: 'FE',
  },
  {
    key: 'whatsapp_no',
    section: 'contact',
    label: 'WhatsApp No (Primary)',
    type: 'mobile',
    help: 'Main number for school WhatsApp',
    store: { t: 'json', on: 'student', key: 'whatsapp_no' },
    excelColumn: 'FF',
  },
  {
    key: 'alternate_mobile',
    section: 'contact',
    label: 'Alternate Mobile',
    type: 'mobile',
    store: { t: 'json', on: 'student', key: 'alternate_mobile' },
    excelColumn: 'FG',
  },
  {
    key: 'primary_email',
    section: 'contact',
    label: 'Primary Email',
    type: 'email',
    help: 'Main email for school communication',
    store: { t: 'json', on: 'student', key: 'primary_email' },
    excelColumn: 'FH',
  },
  {
    key: 'student_own_mobile',
    section: 'contact',
    label: 'Student’s Own Mobile',
    type: 'mobile',
    help: 'Used when a message is sent to the student (not the parents)',
    store: { t: 'json', on: 'student', key: 'student_own_mobile' },
    excelColumn: 'GJ',
  },
  {
    key: 'student_own_email',
    section: 'contact',
    label: 'Student’s Own Email',
    type: 'email',
    help: 'Used when a message is sent to the student (not the parents)',
    store: { t: 'json', on: 'student', key: 'student_own_email' },
    excelColumn: 'GK',
  },
  {
    key: 'emergency_contact_name',
    section: 'contact',
    label: 'Emergency Contact Name',
    type: 'text',
    required: true,
    help: 'Person to call if parents are not reachable',
    store: { t: 'json', on: 'student', key: 'emergency_contact_name' },
    excelColumn: 'FI',
  },
  {
    key: 'emergency_contact_relation',
    section: 'contact',
    label: 'Emergency Contact Relation',
    type: 'list',
    list: 'Relation',
    store: { t: 'json', on: 'student', key: 'emergency_contact_relation' },
    excelColumn: 'FJ',
  },
  {
    key: 'emergency_contact_mobile',
    section: 'contact',
    label: 'Emergency Contact Mobile',
    type: 'mobile',
    required: true,
    store: { t: 'json', on: 'student', key: 'emergency_contact_mobile' },
    excelColumn: 'FK',
  },
  {
    key: 'sibling_in_school',
    section: 'sibling',
    label: 'Sibling in School',
    type: 'list',
    required: true,
    list: 'YesNo',
    store: { t: 'json', on: 'student', key: 'sibling_in_school' },
    excelColumn: 'FL',
  },
  {
    key: 'sibling_name',
    section: 'sibling',
    label: 'Sibling Name',
    type: 'text',
    help: 'Only if Yes',
    when: { key: 'sibling_in_school', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'sibling_name' },
    excelColumn: 'FM',
  },
  {
    key: 'sibling_admission_no',
    section: 'sibling',
    label: 'Sibling Admission No',
    type: 'text',
    when: { key: 'sibling_in_school', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'sibling_admission_no' },
    excelColumn: 'FN',
  },
  {
    key: 'sibling_class_section',
    section: 'sibling',
    label: 'Sibling Class-Section',
    type: 'text',
    help: 'e.g. IV-B',
    when: { key: 'sibling_in_school', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'sibling_class_section' },
    excelColumn: 'FO',
  },
  {
    key: 'transport_required',
    retired: true,
    section: 'transport_health',
    label: 'Transport Required',
    type: 'list',
    list: 'YesNo',
    store: { t: 'json', on: 'student', key: 'transport_required' },
    excelColumn: 'FP',
  },
  {
    key: 'travel_mode',
    retired: true,
    section: 'transport_health',
    label: 'Travel Mode',
    type: 'list',
    list: 'TravelMode',
    when: { key: 'transport_required', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'travel_mode' },
    excelColumn: 'FQ',
  },
  {
    key: 'route_no',
    retired: true,
    section: 'transport_health',
    label: 'Route No',
    type: 'text',
    help: 'Filled by transport office',
    when: { key: 'transport_required', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'route_no' },
    excelColumn: 'FR',
  },
  {
    key: 'cwsn',
    section: 'transport_health',
    label: 'Child with Special Needs (CWSN)',
    type: 'list',
    required: true,
    list: 'YesNo',
    help: 'Specially-abled / disability',
    store: { t: 'json', on: 'student', key: 'cwsn' },
    excelColumn: 'FS',
  },
  {
    key: 'type_of_disability',
    section: 'transport_health',
    label: 'Type of Disability',
    type: 'list',
    list: 'Disability',
    help: 'Only if CWSN = Yes',
    when: { key: 'cwsn', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'type_of_disability' },
    excelColumn: 'FT',
  },
  {
    key: 'disability_percent',
    section: 'transport_health',
    label: 'Disability %',
    type: 'number',
    help: 'As per certificate (0-100)',
    when: { key: 'cwsn', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'disability_percent' },
    excelColumn: 'FU',
  },
  {
    key: 'disability_certificate_no',
    section: 'transport_health',
    label: 'Disability Certificate No',
    type: 'text',
    help: 'UDID / medical certificate number',
    when: { key: 'cwsn', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'disability_certificate_no' },
    excelColumn: 'FV',
  },
  {
    key: 'special_needs_details',
    section: 'transport_health',
    label: 'Special Needs Details / Reason',
    type: 'text',
    help: 'Describe the condition, support or therapy needed',
    when: { key: 'cwsn', in: ['Yes'] },
    store: { t: 'json', on: 'student', key: 'special_needs_details' },
    excelColumn: 'FW',
  },
  {
    key: 'medical_condition',
    section: 'transport_health',
    label: 'Medical Condition / Allergy',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'medical_condition' },
    excelColumn: 'FX',
  },
  {
    key: 'account_holder_name',
    section: 'bank',
    label: 'Account Holder Name',
    type: 'text',
    help: 'As printed on passbook / cheque',
    store: { t: 'json', on: 'student', key: 'account_holder_name' },
    excelColumn: 'FY',
  },
  {
    key: 'bank_name',
    section: 'bank',
    label: 'Bank Name',
    type: 'list',
    list: 'Bank',
    store: { t: 'json', on: 'student', key: 'bank_name' },
    excelColumn: 'FZ',
  },
  {
    key: 'bank_account_no',
    section: 'bank',
    label: 'Bank Account No',
    type: 'account',
    help: '9 to 18 digits',
    sensitive: true,
    store: { t: 'secure', on: 'student', key: 'bank_account_no' },
    excelColumn: 'GA',
  },
  {
    key: 'ifsc_code',
    section: 'bank',
    label: 'IFSC Code',
    type: 'ifsc',
    help: '11 characters, 5th is 0 — e.g. SBIN0001234',
    store: { t: 'json', on: 'student', key: 'ifsc_code' },
    excelColumn: 'GB',
  },
  {
    key: 'bank_branch_name',
    section: 'bank',
    label: 'Bank Branch Name',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'bank_branch_name' },
    excelColumn: 'GC',
  },
  {
    key: 'bank_branch_address',
    section: 'bank',
    label: 'Bank Branch Address',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'bank_branch_address' },
    excelColumn: 'GD',
  },
  {
    key: 'birth_certificate_submitted',
    section: 'documents',
    label: 'Birth Certificate Submitted',
    type: 'list',
    required: true,
    list: 'YesNo',
    store: { t: 'json', on: 'student', key: 'birth_certificate_submitted' },
    excelColumn: 'GE',
  },
  {
    key: 'residence_proof_submitted',
    section: 'documents',
    label: 'Residence Proof Submitted',
    type: 'list',
    required: true,
    list: 'YesNo',
    store: { t: 'json', on: 'student', key: 'residence_proof_submitted' },
    excelColumn: 'GF',
  },
  {
    key: 'student_photo_submitted',
    section: 'documents',
    label: 'Student Photo Submitted',
    type: 'list',
    required: true,
    list: 'YesNo',
    store: { t: 'json', on: 'student', key: 'student_photo_submitted' },
    excelColumn: 'GG',
  },
  {
    key: 'aadhaar_copy_submitted',
    section: 'documents',
    label: 'Aadhaar Copy Submitted',
    type: 'list',
    list: 'YesNo',
    store: { t: 'json', on: 'student', key: 'aadhaar_copy_submitted' },
    excelColumn: 'GH',
  },
  {
    key: 'remarks',
    section: 'documents',
    label: 'Remarks',
    type: 'text',
    store: { t: 'json', on: 'student', key: 'remarks' },
    excelColumn: 'GI',
  },
];

/** Default dropdown values, preloaded into each school's `profile_lists` master. */
export const PROFILE_LIST_DEFAULTS: Record<string, string[]> = {
  House: ['Red', 'Blue', 'Green', 'Yellow'],
  YesNo: ['Yes', 'No'],
  Gender: ['Male', 'Female', 'Other'],
  BloodGroup: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Not Known'],
  Religion: ['Hindu', 'Muslim', 'Sikh', 'Christian', 'Jain', 'Buddhist', 'Parsi', 'Other'],
  Category: ['General', 'OBC', 'OBC (Non-Creamy Layer)', 'SC', 'ST', 'Other'],
  // starter values; each school keeps its own list in Setup → Student profile lists (SubCaste)
  SubCaste: [
    'Agarwal',
    'Arora',
    'Baniya',
    'Bhumihar',
    'Brahmin',
    'Gujjar',
    'Jat',
    'Jatav',
    'Kayastha',
    'Khatri',
    'Kurmi',
    'Kushwaha',
    'Lodhi',
    'Maratha',
    'Meena',
    'Rajput',
    'Saini',
    'Sindhi',
    'Valmiki',
    'Yadav',
    'Other',
  ],
  Disability: [
    'Locomotor Disability',
    'Visual Impairment (Blindness)',
    'Low Vision',
    'Hearing Impairment',
    'Speech & Language Disability',
    'Intellectual Disability',
    'Specific Learning Disability',
    'Autism Spectrum Disorder',
    'ADHD',
    'Cerebral Palsy',
    'Multiple Disabilities',
    'Chronic Neurological Condition',
    'Other',
  ],
  Nationality: ['Indian', 'American', 'British', 'Canadian', 'Other'],
  MotherTongue: [
    'Hindi',
    'English',
    'Punjabi',
    'Tamil',
    'Marathi',
    'Gujarati',
    'Maithili',
    'Bengali',
    'Telugu',
    'Malayalam',
    'Kannada',
    'Urdu',
    'Other',
  ],
  Class: [
    'Pre-Nursery',
    'Nursery',
    'KG',
    'I',
    'II',
    'III',
    'IV',
    'V',
    'VI',
    'VII',
    'VIII',
    'IX',
    'X',
    'XI',
    'XII',
  ],
  Stream: ['Not Applicable', 'Science (PCM)', 'Science (PCB)', 'Commerce', 'Humanities'],
  Twin: ['No', 'Twin/Triplet Child 1', 'Twin/Triplet Child 2', 'Twin/Triplet Child 3'],
  Education: [
    'Below Matric',
    'Matric (10th)',
    'Senior Secondary (12th)',
    'Diploma',
    'Graduate',
    'Post Graduate',
    'Doctorate',
    'Professional (CA/CS/MBBS/LLB etc.)',
    'Other',
  ],
  Occupation: [
    'Business',
    'Engineer',
    'Management',
    'Finance',
    'Banking',
    'Medical Services',
    'Legal Services',
    'Education',
    'Civil Services',
    'Defence',
    'Consultancy',
    'Hospitality Industry',
    'Human Resource',
    'Secretarial Services',
    'IT / Software',
    'Private Service',
    'Professional',
    'Government Service',
    'Accountancy',
    'Advertising',
    'Artist',
    'Aviation',
    'Event Management',
    'Fashion Industry',
    'Home Maker',
    'Others',
  ],
  Income: [
    'Below 1 Lakh',
    '1-5 Lakh',
    '5-10 Lakh',
    '10-25 Lakh',
    '25-50 Lakh',
    'Above 50 Lakh',
    'Prefer not to say',
  ],
  Relation: [
    'Father',
    'Mother',
    'Grandfather',
    'Grandmother',
    'Uncle',
    'Aunt',
    'Brother',
    'Sister',
    'Other',
  ],
  Distance: ['0-6 Km', '6-8 Km', '8-15 Km', '15 Km & Above'],
  TravelMode: ['Pick and Drop', 'Pick Only', 'Drop Only', 'Not Required'],
  SingleParent: ['Not Applicable', 'Mother Only', 'Father Only', 'Guardian'],
  State: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
    'Outside India',
  ],
  Country: ['India', 'USA', 'UK', 'Canada', 'UAE', 'Australia', 'Singapore', 'Nepal', 'Other'],
  AlumniClass: ['X', 'XII'],
  Board: ['CBSE', 'ICSE / ISC', 'State Board', 'IB', 'Cambridge (IGCSE)', 'NIOS', 'Other'],
  Boarding: ['Day Scholar', 'Hosteller'],
};

export const PROFILE_FIELD_BY_KEY: ReadonlyMap<string, ProfileField> = new Map(
  PROFILE_FIELDS.map((f) => [f.key, f]),
);

/** Fields a user can type into (not enrolment-owned, not computed). */
export const EDITABLE_PROFILE_FIELDS = PROFILE_FIELDS.filter(
  (f) => f.store.t !== 'auto' && f.store.t !== 'enrol' && !f.retired,
);

/** The quick-add form: the minimum the ERP needs on day one (fees, attendance, SMS, class lists). */
export const QUICK_ADD_KEYS = [
  'admission_no',
  'first_name',
  'last_name',
  'dob',
  'gender',
  'admitted_on',
  'father_name',
  'mother_name',
  'sms_mobile',
  'category',
  'ews',
  'boarding',
] as const;

/**
 * Fields a family may ask to change from the parent app (approved by the office before they apply).
 * Names, category, EWS, ID numbers, bank details, documents and class stay with the office.
 */
export const FAMILY_EDITABLE_KEYS: readonly string[] = [
  'blood_group',
  'mother_tongue',
  'place_of_birth',
  'medical_condition',
  'sms_mobile',
  'whatsapp_no',
  'alternate_mobile',
  'primary_email',
  'emergency_contact_name',
  'emergency_contact_relation',
  'emergency_contact_mobile',
  'residential_address_line_1',
  'residential_address_line_2',
  'residential_address_line_3',
  'residential_city',
  'residential_state',
  'residential_country',
  'residential_pin_code',
  'permanent_same',
  'permanent_address_line_1',
  'permanent_address_line_2',
  'permanent_address_line_3',
  'permanent_city',
  'permanent_state',
  'permanent_country',
  'permanent_pin_code',
  'distance_from_school',
  ...(['father', 'mother', 'guardian'] as const).flatMap((p) =>
    [
      'date_of_birth',
      'nationality',
      'mobile',
      'whatsapp_no',
      'email',
      'education',
      'occupation',
      'designation',
      'organisation',
      'annual_income',
      'office_address_line_1',
      'office_address_line_2',
      'office_address_line_3',
      'office_city',
      'office_state',
      'office_country',
      'office_pin_code',
      'dps_alumni',
      'alumni_school_branch',
      'alumni_school_city_state',
      'alumni_passing_class',
      'alumni_passing_year',
      'alumni_cbse_roll_no',
    ].map((k) => `${p}_${k}`),
  ),
];
