-- Student 360 profile (post-freeze change, 2026-09-30).
-- The data collection sheet (Student_Information_Collection.xlsx) defines ~190 fields. Core fields keep
-- their columns; the rest live in validated JSONB keyed by the catalogue in packages/db/src/student-fields.ts:
--   students.profile / guardians.profile  plain values
--   students.secure  / guardians.secure   AES-256-GCM ciphertext (Aadhaar, PAN, bank account), see field-crypto.ts
-- Dropdown lists become a school-editable master (profile_lists), preloaded from the sheet's Lists tab.

ALTER TABLE students
  ADD COLUMN profile              JSONB    NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN secure               JSONB    NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN profile_completeness SMALLINT NOT NULL DEFAULT 0 CHECK (profile_completeness BETWEEN 0 AND 100);
ALTER TABLE guardians
  ADD COLUMN profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN secure  JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Registration numbers are looked up by the import and must stay unique within a school.
CREATE UNIQUE INDEX students_registration_no_uq ON students (school_id, (profile ->> 'registration_no'))
  WHERE deleted_at IS NULL AND profile ? 'registration_no';
CREATE INDEX students_profile_gin ON students USING gin (profile jsonb_path_ops);

-- Existing admissions wrote the previous school into details; carry it into the catalogue key.
UPDATE students
   SET profile = profile || jsonb_build_object('previous_school_name', details ->> 'previousSchool')
 WHERE details ? 'previousSchool' AND COALESCE(details ->> 'previousSchool', '') <> '';

CREATE TABLE profile_lists (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  school_id  BIGINT NOT NULL REFERENCES schools(id),
  list_code  TEXT NOT NULL,
  value      TEXT NOT NULL,
  sort_order INT  NOT NULL DEFAULT 0,
  status     row_status NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by BIGINT,
  UNIQUE (school_id, list_code, value)
);
CALL app.apply_tenant_rls('profile_lists');

INSERT INTO profile_lists (school_id, list_code, value, sort_order)
SELECT s.id, v.list_code, v.value, v.sort_order
  FROM schools s
 CROSS JOIN (VALUES
  ('YesNo', 'Yes', 1),
  ('YesNo', 'No', 2),
  ('Gender', 'Male', 1),
  ('Gender', 'Female', 2),
  ('Gender', 'Other', 3),
  ('BloodGroup', 'A+', 1),
  ('BloodGroup', 'A-', 2),
  ('BloodGroup', 'B+', 3),
  ('BloodGroup', 'B-', 4),
  ('BloodGroup', 'AB+', 5),
  ('BloodGroup', 'AB-', 6),
  ('BloodGroup', 'O+', 7),
  ('BloodGroup', 'O-', 8),
  ('BloodGroup', 'Not Known', 9),
  ('Religion', 'Hindu', 1),
  ('Religion', 'Muslim', 2),
  ('Religion', 'Sikh', 3),
  ('Religion', 'Christian', 4),
  ('Religion', 'Jain', 5),
  ('Religion', 'Buddhist', 6),
  ('Religion', 'Parsi', 7),
  ('Religion', 'Other', 8),
  ('Category', 'General', 1),
  ('Category', 'OBC', 2),
  ('Category', 'OBC (Non-Creamy Layer)', 3),
  ('Category', 'SC', 4),
  ('Category', 'ST', 5),
  ('Category', 'Other', 6),
  ('Disability', 'Locomotor Disability', 1),
  ('Disability', 'Visual Impairment (Blindness)', 2),
  ('Disability', 'Low Vision', 3),
  ('Disability', 'Hearing Impairment', 4),
  ('Disability', 'Speech & Language Disability', 5),
  ('Disability', 'Intellectual Disability', 6),
  ('Disability', 'Specific Learning Disability', 7),
  ('Disability', 'Autism Spectrum Disorder', 8),
  ('Disability', 'ADHD', 9),
  ('Disability', 'Cerebral Palsy', 10),
  ('Disability', 'Multiple Disabilities', 11),
  ('Disability', 'Chronic Neurological Condition', 12),
  ('Disability', 'Other', 13),
  ('Nationality', 'Indian', 1),
  ('Nationality', 'American', 2),
  ('Nationality', 'British', 3),
  ('Nationality', 'Canadian', 4),
  ('Nationality', 'Other', 5),
  ('MotherTongue', 'Hindi', 1),
  ('MotherTongue', 'English', 2),
  ('MotherTongue', 'Punjabi', 3),
  ('MotherTongue', 'Tamil', 4),
  ('MotherTongue', 'Marathi', 5),
  ('MotherTongue', 'Gujarati', 6),
  ('MotherTongue', 'Maithili', 7),
  ('MotherTongue', 'Bengali', 8),
  ('MotherTongue', 'Telugu', 9),
  ('MotherTongue', 'Malayalam', 10),
  ('MotherTongue', 'Kannada', 11),
  ('MotherTongue', 'Urdu', 12),
  ('MotherTongue', 'Other', 13),
  ('Class', 'Pre-Nursery', 1),
  ('Class', 'Nursery', 2),
  ('Class', 'KG', 3),
  ('Class', 'I', 4),
  ('Class', 'II', 5),
  ('Class', 'III', 6),
  ('Class', 'IV', 7),
  ('Class', 'V', 8),
  ('Class', 'VI', 9),
  ('Class', 'VII', 10),
  ('Class', 'VIII', 11),
  ('Class', 'IX', 12),
  ('Class', 'X', 13),
  ('Class', 'XI', 14),
  ('Class', 'XII', 15),
  ('Stream', 'Not Applicable', 1),
  ('Stream', 'Science (PCM)', 2),
  ('Stream', 'Science (PCB)', 3),
  ('Stream', 'Commerce', 4),
  ('Stream', 'Humanities', 5),
  ('Twin', 'No', 1),
  ('Twin', 'Twin/Triplet Child 1', 2),
  ('Twin', 'Twin/Triplet Child 2', 3),
  ('Twin', 'Twin/Triplet Child 3', 4),
  ('Education', 'Below Matric', 1),
  ('Education', 'Matric (10th)', 2),
  ('Education', 'Senior Secondary (12th)', 3),
  ('Education', 'Diploma', 4),
  ('Education', 'Graduate', 5),
  ('Education', 'Post Graduate', 6),
  ('Education', 'Doctorate', 7),
  ('Education', 'Professional (CA/CS/MBBS/LLB etc.)', 8),
  ('Education', 'Other', 9),
  ('Occupation', 'Business', 1),
  ('Occupation', 'Engineer', 2),
  ('Occupation', 'Management', 3),
  ('Occupation', 'Finance', 4),
  ('Occupation', 'Banking', 5),
  ('Occupation', 'Medical Services', 6),
  ('Occupation', 'Legal Services', 7),
  ('Occupation', 'Education', 8),
  ('Occupation', 'Civil Services', 9),
  ('Occupation', 'Defence', 10),
  ('Occupation', 'Consultancy', 11),
  ('Occupation', 'Hospitality Industry', 12),
  ('Occupation', 'Human Resource', 13),
  ('Occupation', 'Secretarial Services', 14),
  ('Occupation', 'IT / Software', 15),
  ('Occupation', 'Private Service', 16),
  ('Occupation', 'Professional', 17),
  ('Occupation', 'Government Service', 18),
  ('Occupation', 'Accountancy', 19),
  ('Occupation', 'Advertising', 20),
  ('Occupation', 'Artist', 21),
  ('Occupation', 'Aviation', 22),
  ('Occupation', 'Event Management', 23),
  ('Occupation', 'Fashion Industry', 24),
  ('Occupation', 'Home Maker', 25),
  ('Occupation', 'Others', 26),
  ('Income', 'Below 1 Lakh', 1),
  ('Income', '1-5 Lakh', 2),
  ('Income', '5-10 Lakh', 3),
  ('Income', '10-25 Lakh', 4),
  ('Income', '25-50 Lakh', 5),
  ('Income', 'Above 50 Lakh', 6),
  ('Income', 'Prefer not to say', 7),
  ('Relation', 'Father', 1),
  ('Relation', 'Mother', 2),
  ('Relation', 'Grandfather', 3),
  ('Relation', 'Grandmother', 4),
  ('Relation', 'Uncle', 5),
  ('Relation', 'Aunt', 6),
  ('Relation', 'Brother', 7),
  ('Relation', 'Sister', 8),
  ('Relation', 'Other', 9),
  ('Distance', '0-6 Km', 1),
  ('Distance', '6-8 Km', 2),
  ('Distance', '8-15 Km', 3),
  ('Distance', '15 Km & Above', 4),
  ('TravelMode', 'Pick and Drop', 1),
  ('TravelMode', 'Pick Only', 2),
  ('TravelMode', 'Drop Only', 3),
  ('TravelMode', 'Not Required', 4),
  ('SingleParent', 'Not Applicable', 1),
  ('SingleParent', 'Mother Only', 2),
  ('SingleParent', 'Father Only', 3),
  ('SingleParent', 'Guardian', 4),
  ('State', 'Andhra Pradesh', 1),
  ('State', 'Arunachal Pradesh', 2),
  ('State', 'Assam', 3),
  ('State', 'Bihar', 4),
  ('State', 'Chhattisgarh', 5),
  ('State', 'Goa', 6),
  ('State', 'Gujarat', 7),
  ('State', 'Haryana', 8),
  ('State', 'Himachal Pradesh', 9),
  ('State', 'Jharkhand', 10),
  ('State', 'Karnataka', 11),
  ('State', 'Kerala', 12),
  ('State', 'Madhya Pradesh', 13),
  ('State', 'Maharashtra', 14),
  ('State', 'Manipur', 15),
  ('State', 'Meghalaya', 16),
  ('State', 'Mizoram', 17),
  ('State', 'Nagaland', 18),
  ('State', 'Odisha', 19),
  ('State', 'Punjab', 20),
  ('State', 'Rajasthan', 21),
  ('State', 'Sikkim', 22),
  ('State', 'Tamil Nadu', 23),
  ('State', 'Telangana', 24),
  ('State', 'Tripura', 25),
  ('State', 'Uttar Pradesh', 26),
  ('State', 'Uttarakhand', 27),
  ('State', 'West Bengal', 28),
  ('State', 'Andaman and Nicobar Islands', 29),
  ('State', 'Chandigarh', 30),
  ('State', 'Dadra and Nagar Haveli and Daman and Diu', 31),
  ('State', 'Delhi', 32),
  ('State', 'Jammu and Kashmir', 33),
  ('State', 'Ladakh', 34),
  ('State', 'Lakshadweep', 35),
  ('State', 'Puducherry', 36),
  ('State', 'Outside India', 37),
  ('Country', 'India', 1),
  ('Country', 'USA', 2),
  ('Country', 'UK', 3),
  ('Country', 'Canada', 4),
  ('Country', 'UAE', 5),
  ('Country', 'Australia', 6),
  ('Country', 'Singapore', 7),
  ('Country', 'Nepal', 8),
  ('Country', 'Other', 9),
  ('AlumniClass', 'X', 1),
  ('AlumniClass', 'XII', 2),
  ('Board', 'CBSE', 1),
  ('Board', 'ICSE / ISC', 2),
  ('Board', 'State Board', 3),
  ('Board', 'IB', 4),
  ('Board', 'Cambridge (IGCSE)', 5),
  ('Board', 'NIOS', 6),
  ('Board', 'Other', 7),
  ('Boarding', 'Day Scholar', 1),
  ('Boarding', 'Hosteller', 2)
 ) AS v(list_code, value, sort_order)
ON CONFLICT (school_id, list_code, value) DO NOTHING;

-- Full Aadhaar / PAN / bank account values: granted only through the role below, which the admin assigns
-- to named users (Access → assignments). Everyone else sees XXXX-XXXX-1234.
INSERT INTO permissions (code, module, description, requires_mfa) VALUES
  ('people.sensitive.view', 'people', 'See full Aadhaar, PAN and bank account numbers of students and parents', false)
ON CONFLICT (code) DO NOTHING;

INSERT INTO roles (school_id, code, name, kind, is_system, description) VALUES
  (NULL, 'sensitive_data_viewer', 'Sensitive data viewer', 'module', true,
   'Sees full Aadhaar, PAN and bank account numbers; assign only to the users who need them')
ON CONFLICT (school_id, code) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.id, 'people.sensitive.view' FROM roles r
 WHERE r.school_id IS NULL AND r.code = 'sensitive_data_viewer'
ON CONFLICT DO NOTHING;
