import { Body, Controller, Get, Param, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import { DATASETS } from '@edupro/db';
import { RequirePermission } from '../../common/access/require-permission.decorator';
import { ReqCtx, requireTenant, type RequestContext } from '../../common/http/request-context';
import { CreateExportDto, ListExportsQueryDto } from './reports.dto';
import { REPORTS } from './reports.permissions';
import { ReportsService } from './reports.service';

@ApiTags('reports')
@ApiBearerAuth()
@Controller('reports')
export class ReportsController {
  constructor(private readonly reports: ReportsService) {}

  @Get('datasets')
  @ApiOperation({ summary: 'Datasets the caller may export' })
  @RequirePermission(REPORTS.exportView, { description: 'View and download exports' })
  datasets(@ReqCtx() ctx: RequestContext) {
    const held = ctx.permissions ?? new Set<string>();
    return {
      data: Object.values(DATASETS)
        .filter((d) => held.has(d.permission))
        .map((d) => ({
          id: d.id,
          title: d.title,
          columns: d.columns.map((c) => c.header),
          maxRows: d.maxRows,
        })),
    };
  }

  @Get('exports')
  @RequirePermission(REPORTS.exportView)
  async list(@ReqCtx() ctx: RequestContext, @Query() q: ListExportsQueryDto) {
    // Sprint 14: families (no export.create) see their own exports only
    const { rows, total } = await this.reports.list(
      requireTenant(ctx),
      q,
      !ctx.permissions?.has(REPORTS.exportCreate),
    );
    return { data: rows, page: { number: q.page, size: q.size, total } };
  }

  @Post('exports')
  @ApiOperation({ summary: 'Request an export; the file is generated by a worker' })
  @RequirePermission(REPORTS.exportCreate, { description: 'Request PDF, Excel and CSV exports' })
  create(@ReqCtx() ctx: RequestContext, @Body() body: CreateExportDto) {
    return this.reports.create(ctx, body);
  }

  @Get('exports/:id')
  @ApiOperation({ summary: 'Export status and, when ready, a signed download URL' })
  @RequirePermission(REPORTS.exportView)
  status(@ReqCtx() ctx: RequestContext, @Param('id') id: string) {
    return this.reports.status(ctx, id);
  }
}
